config/routes.rb
Tfpullrequests::Application.routes.draw do
  resources :users
  resources :projects, :only => [:index, :new, :create]
  resource  :dashboard # Singular, only applies to current user
  resource  :pull_request_download, :only => :create

  match '/email', to: 'dashboards#email', as: 'email'
  match '/email/update', to: 'dashboards#update_email', as: 'update_email'

  match '/login',  to: 'sessions#new',     as: 'login'
  match '/logout', to: 'sessions#destroy', as: 'logout'

  match '/auth/:provider/callback', to: 'sessions#create'
  match '/auth/failure',            to: 'sessions#failure'

  match 'about', :to => 'static#about'
  match 'contributing', :to => 'static#contributing'

  root :to => 'static#homepage'

  match '/:id', to: 'users#show' # User public vanity url, must be lowest priority
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  before_filter :ensure_logged_in
  before_filter :set_email_preferences, :except => [:email, :update_email]

  def show
    pull_requests = current_user.pull_requests
    projects = Project.where(:main_language => current_user.languages).limit(100).sample(12).sort_by(&:name)
    render :show, :locals => { :user => current_user, :pull_requests => pull_requests, :projects => projects }
  end

  def update_email
    current_user.skills.delete_all
    if current_user.update_attributes(params[:user])
      redirect_to dashboard_path
    else
      render :email
    end
  end

  protected

  def set_email_preferences
    redirect_to email_path unless current_user.email_frequency.present?
  end
end

app/views/dashboards/_pull_requests_if_any.html.haml
- if pull_requests.any?
  %ul
    = render :partial => 'pull_requests/pull_request', :collection => pull_requests
- else
  %p You've not sent any pull requests, what are you waiting for?!

app/views/dashboards/email.html.haml
%h2 Set your Email Preferences 

= simple_form_for current_user, :url => update_email_path, :html => {:class => 'form-horizontal'}  do |form|
  = form.input :email
  = form.input :email_frequency, :collection => [['Never', 'none'], ['Daily', 'daily'], ['Weekly', 'weekly']], :selected => 'daily'

  %h3 Which languages do you know?
  #skills.clearfix
    = form.simple_fields_for :skills, Project::LANGUAGES.map{|l| Skill.new(:language => l)} do |skill_form|
      - language = skill_form.object.language
      .control-group.string
        %label.control-label{:for => language}= language
        .controls
          = skill_form.check_box :language, {:id => language, :checked => current_user.skills.map(&:language).include?(language)}, language

  .control-group
    .controls
      = form.button :submit, 'Save and Continue'

app/views/dashboards/show.html.haml
%h2
  Welcome back #{user.nickname}

%p This is where you can see all the activity we've tracked for in the run up to Xmas.

%hr

%h3 Your Pull Requests

%div#pull-requests
  = render :partial => 'pull_requests_if_any', :locals => { :pull_requests => current_user.pull_requests }

= link_to 'Syncronize Pull Requests Now', pull_request_download_path, :id => 'fetch-pull-requests', :class => 'btn pull-right'

%hr
.row-fluid.clearfix
  .span12
    %h3
      Suggested Projects
      = link_to 'Suggest a project', new_project_path, :class => 'btn pull-right'
      = link_to 'View All', projects_path, :class => 'btn pull-right'
    %p
      Can't think of a project you would like to help out? We've put together a list of popular projects.

  #projects
    = render projects