config/routes.rb
Tfpullrequests::Application.routes.draw do
  resources :users
  resources :projects, :only => [:index, :new, :create]
  resource  :dashboard # Singular, only applies to current user
  resource  :pull_request_download, :only => :create

  match '/email', to: 'dashboards#email', as: 'email'
  match '/email/update', to: 'dashboards#update_email', as: 'update_email'

  match '/login',  to: 'sessions#new',     as: 'login'
  match '/logout', to: 'sessions#destroy', as: 'logout'

  match '/auth/:provider/callback', to: 'sessions#create'
  match '/auth/failure',            to: 'sessions#failure'

  match 'about', :to => 'static#about'
  match 'contributing', :to => 'static#contributing'

  root :to => 'static#homepage'

  match '/:id', to: 'users#show' # User public vanity url, must be lowest priority
end

app/views/layouts/application.html.haml
!!!
%html{ :lang => 'en' }
  %head
    %meta{ :charset => "utf-8" }
    %meta{ :'http-equiv' => 'X-UA-Compatible', :content => "IE=Edge,chrome=1" }
    %meta{ :name => "viewport", :content => "user-scalable=no, width=device-width, initial-scale=1.0, maximum-scale=1.0;"  }
    %title= content_for?(:title) ? yield(:title) : "24 Pull Requests"
    = csrf_meta_tags

    :plain
      <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
      <!--[if lt IE 9]>
        <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
      <![endif]-->

    = stylesheet_link_tag "application", :media => "all"

    /  For third-generation iPad with high-resolution Retina display:
    /  Size should be 144 x 144 pixels
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'

    / For iPhone with high-resolution Retina display:
    / Size should be 114 x 114 pixels
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'

    / For first- and second-generation iPad:
    / Size should be 72 x 72 pixels
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'

    / For non-Retina iPhone, iPod Touch, and Android 2.1+ devices:
    / Size should be 57 x 57 pixels
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'

    / For all other devices
    / Size should be 32 x 32 pixels
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'
    %script(type="text/javascript" src="//use.typekit.net/ghm4aoe.js")
    :javascript
      try{Typekit.load();}catch(e){}
  %body
    = content_for :body_open unless content_for(:body_open).nil?

    %a.forkme{ :href => "https://github.com/andrew/24pullrequests", :target => '_blank'}
      %img{ :src => 'https://s3.amazonaws.com/github/ribbons/forkme_right_white_ffffff.png', :alt => 'Fork me on GitHub'}


    .header-background

    %header
      .bar
      .logo
        = link_to 'homepage', root_path

      - # It sucks but its quick! Sorry
      - if params[:action] == 'homepage'
        .tagline.hidden-phone

      = render :partial => 'user_nav'

    %article
      .container-fluid
        .row-fluid
          .span12
            = yield

  %footer
    .dark
      .dark-inner
        .logo.logo-dark
        %ul.unstyled.pull-right
          %li
            Sponsored by&nbsp;
            = link_to 'DNSimple', 'http://dnsimple.com'
            &nbsp;&amp;&nbsp;
            = link_to 'Cooper Press', 'http://cooperpress.com'
            
        %ul.unstyled.pull-left
          %li
            = link_to 'About', about_path

    .ftw
      Open Source FTW!
      %strong 2012

    = javascript_include_tag "application"